const data2=[
    {
        id:1,
        title:"Love Beauty & Planet Coffee & Warm Vanilla Body Wash",
        price:"224",
        oldPrice:"300",
        rating:"4",
        reviews:"116",
        offer:"12",
        img:"src/Components/ProductListPage/Assets/1.png",
        company:"Love Beauty & Planet",
        productType:"body wash",
        skinType:["dry skin","dry sensitive"],
        concern:["dryness"],
        ingredients:["vitamin c","vitamin e"],
        preferences:[]
    },

    {
        id:2,
        title:"Nivea Frangipani & Oil Body Wash And Shower Gel ",
        price:"255",
        oldPrice:"300",
        rating:"",
        reviews:"",
        offer:"12",
        img:"src/Components/ProductListPage/Assets/2.png",
        productType:"body wash",
        skinType:["oily skin","oily sensitive"],
        concern:[],
        ingredients:[],
        preferences:[]
    },
    {
        id:3,
        title:"Plum BodyLovin' Hawaiian Rumba Shower Gel",
        price:"292",
        oldPrice:"320",
        rating:"",
        reviews:"",
        offer:"12",
        img:"src/Components/ProductListPage/Assets/3.png",
        productType:"shower gel",
        skinType:[],
        concern:[],
        ingredients:[],
        preferences:[]
    },
    {
        id:4,
        title:"Dove Deeply Nourishing Body Wash for smoother skin",
        price:"308",
        oldPrice:"300",
        rating:"",
        reviews:"",
        offer:"12",
        img:"src/Components/ProductListPage/Assets/4.png",
        productType:"body wash",
        skinType:[],
        concern:[],
        ingredients:[],
        preferences:[]
    },
    {
        id:5,
        title:"Pears Soft and Fresh Soap Bar, 125g (Buy 4 Get 1 Free)",
        price:"474",
        oldPrice:"695",
        rating:"",
        reviews:"",
        offer:"20",
        img:"src/Components/ProductListPage/Assets/5.png",
        productType:"body soaps",
        skinType:["dry skin","dry sensitive"],
        concern:["dryness"],
        ingredients:["vitamin c","vitamin e"],
        preferences:[]
    },
    {
        id:6,
        title:"Mamaearth Neem Body Scrub with Neem & Tulsi",
        price:"449",
        oldPrice:"695",
        rating:"",
        reviews:"",
        offer:"20",
        img:"src/Components/ProductListPage/Assets/6.png",
        productType:"body scrubs",
        skinType:["oily skin","oily sensitive"],
        concern:[],
        ingredients:[],
        preferences:[]
    },
    {
        id:7,
        title:"Dr. Sheth’s Neem & Salicylic Acid Body Wash For Body Acne",
        price:"349",
        oldPrice:"396",
        rating:"",
        reviews:"",
        offer:"12",
        img:"src/Components/ProductListPage/Assets/7.png",
        productType:"body wash",
        skinType:[],
        concern:[],
        ingredients:[],
        preferences:[]
    },
    {
        id:8,
        title:"Dot & Key Booty Polish Deep Exfoliating Walnut & Coffee Body Scrub,",
        price:"629",
        oldPrice:"720",
        rating:"",
        reviews:"",
        offer:"20",
        img:"src/Components/ProductListPage/Assets/8.png",
        productType:"body scrubs",
        skinType:[],
        concern:[],
        ingredients:[],
        preferences:[]
    },
    {
        id:9,
        title:"Dove Cream Beauty Bathing Bar",
        price:"60",
        oldPrice:"",
        rating:"",
        reviews:"",
        offer:"",
        img:"src/Components/ProductListPage/Assets/9.png",
        productType:"body soaps",
        skinType:["dry skin","dry sensitive"],
        concern:["dryness"],
        ingredients:["vitamin c","vitamin e"],
        preferences:[]
    },
    {
        id:10,
        title:"Cetaphil Restoraderm Skin Restoring Body Wash",
        price:"1684",
        oldPrice:"1834",
        rating:"",
        reviews:"",
        offer:"8",
        img:"src/Components/ProductListPage/Assets/10.png",
        productType:"body wash",
        skinType:["oily skin","oily sensitive"],
        concern:[],
        ingredients:[],
        preferences:[]
    },
    {
        id:11,
        title:"Salicylic Acid Body Wash - 1% salicylic acid + 2% glycolic acid ",
        price:"332",
        oldPrice:"449",
        rating:"",
        reviews:"",
        offer:"26",
        img:"src/Components/ProductListPage/Assets/11.png",
        productType:"body wash",
        skinType:[],
        concern:[],
        ingredients:[],
        preferences:[]
    },
    {
        id:12,
        title:"Exfoliating Cherry Blossom & Tea Rose Body Scrub ",
        price:"525",
        oldPrice:"630",
        rating:"",
        reviews:"",
        offer:"26",
        img:"src/Components/ProductListPage/Assets/12.png",
        productType:"body scrubs",
        skinType:[],
        concern:[],
        ingredients:[],
        preferences:[]
    },
    {
        id:13,
        title:"Dove nourishing care in shower argan oil ",
        price:"260",
        oldPrice:"695",
        rating:"",
        reviews:"",
        offer:"20",
        img:"src/Components/ProductListPage/Assets/13.png",
        productType:"shower oils",
        skinType:["dry skin","dry sensitive"],
        concern:["dryness"],
        ingredients:["vitamin c","vitamin e"],
        preferences:[]
    },
    {
        id:14,
        title:"Love Beauty and Planet Bath Bomb, Murumuru Butter and Rose",
        price:"260",
        oldPrice:"695",
        rating:"",
        reviews:"",
        offer:"20",
        img:"src/Components/ProductListPage/Assets/14.png",
        productType:"bath bombs",
        skinType:["oily skin","oily sensitive"],
        concern:[],
        ingredients:[],
        preferences:[]
    },
    {
        id:15,
        title:"Mamaearth Vitamin C Nourishing Bathing Soap With Vitamin C and Honey",
        price:"328",
        oldPrice:"695",
        rating:"",
        reviews:"",
        offer:"20",
        img:"src/Components/ProductListPage/Assets/15.png",
        productType:"bath soaps",
        skinType:[],
        concern:[],
        ingredients:[],
        preferences:[]
    },
    {
        id:16,
        title:"Dot & Key Watermelon Glycolic Fresh & Cool Shower Gel",
        price:"349",
        oldPrice:"695",
        rating:"",
        reviews:"",
        offer:"20",
        img:"src/Components/ProductListPage/Assets/16.png",
        productType:"shower gel",
        skinType:[],
        concern:[],
        ingredients:[],
        preferences:[]
    },
    {
        id:17,
        title:"Love Beauty & Planet Coffee & Warm Vanilla Body Wash ",
        price:"224",
        oldPrice:"300",
        rating:"",
        reviews:"",
        offer:"12",
        img:"src/Components/ProductListPage/Assets/1.png",
        productType:"body wash",
        skinType:["dry skin","dry sensitive"],
        concern:["dryness"],
        ingredients:["vitamin c","vitamin e"],
        preferences:[]
    },
    {
        id:18,
        title:"Nivea Frangipani & Oil Body Wash And Shower Gel ",
        price:"255",
        oldPrice:"300",
        rating:"",
        reviews:"",
        offer:"12",
        img:"src/Components/ProductListPage/Assets/2.png",
        productType:"shower gel",
        skinType:["oily skin","oily sensitive"],
        concern:[],
        ingredients:[],
        preferences:[]
    },
    {
        id:19,
        title:"Plum BodyLovin' Hawaiian Rumba Shower Gel",
        price:"292",
        oldPrice:"320",
        rating:"",
        reviews:"",
        offer:"12",
        img:"src/Components/ProductListPage/Assets/3.png",
        productType:"shower gel",
        skinType:[],
        concern:[],
        ingredients:[],
        preferences:[]
    },
    {
        id:20,
        title:"Dove Deeply Nourishing Body Wash for smoother skin",
        price:"308",
        oldPrice:"300",
        rating:"",
        reviews:"",
        offer:"12",
        img:"src/Components/ProductListPage/Assets/4.png",
        productType:"body wash",
        skinType:[],
        concern:[],
        ingredients:[],
        preferences:[]
    },
    

];
export default data2;